# Form implementation generated from reading ui file 'ProjectHistory.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProjectHistory(object):
    def setupUi(self, ProjectHistory):
        ProjectHistory.setObjectName("ProjectHistory")
        ProjectHistory.resize(472, 300)
        self.gridLayout = QtWidgets.QGridLayout(ProjectHistory)
        self.gridLayout.setObjectName("gridLayout")
        self.ProjectList = QtWidgets.QListWidget(parent=ProjectHistory)
        self.ProjectList.setObjectName("ProjectList")
        self.gridLayout.addWidget(self.ProjectList, 2, 0, 1, 1)
        self.OpenProject = QtWidgets.QPushButton(parent=ProjectHistory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenProject.sizePolicy().hasHeightForWidth())
        self.OpenProject.setSizePolicy(sizePolicy)
        self.OpenProject.setObjectName("OpenProject")
        self.gridLayout.addWidget(self.OpenProject, 3, 0, 1, 1)
        self.ProjectHistory_2 = QtWidgets.QLabel(parent=ProjectHistory)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(12)
        self.ProjectHistory_2.setFont(font)
        self.ProjectHistory_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ProjectHistory_2.setObjectName("ProjectHistory_2")
        self.gridLayout.addWidget(self.ProjectHistory_2, 1, 0, 1, 1)

        self.retranslateUi(ProjectHistory)
        QtCore.QMetaObject.connectSlotsByName(ProjectHistory)

    def retranslateUi(self, ProjectHistory):
        _translate = QtCore.QCoreApplication.translate
        ProjectHistory.setWindowTitle(_translate("ProjectHistory", "Dialog"))
        self.OpenProject.setText(_translate("ProjectHistory", "Open"))
        self.ProjectHistory_2.setText(_translate("ProjectHistory", "Project History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectHistory = QtWidgets.QDialog()
    ui = Ui_ProjectHistory()
    ui.setupUi(ProjectHistory)
    ProjectHistory.show()
    sys.exit(app.exec())
